FROM python:3.11-slim

WORKDIR /app

COPY ../requirements.txt ../utils.py ./

RUN pip install --no-cache-dir -r requirements.txt

COPY ../../database/database.py ../../database/database_utils.py . ../finance.py hourly_pipeline.py ./

CMD ["python", "hourly_pipeline.py"]