FROM python:3.11-slim

WORKDIR /app

COPY collection/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY database ./database
COPY collection/collection_utils.py ./
COPY collection/finance.py ./
COPY collection/hourly_pipeline/hourly_pipeline.py ./
COPY collection/hourly_pipeline/entrypoint.sh ./

CMD ["bash", "entrypoint.sh"]