FROM python:3.11-slim

WORKDIR /app

COPY ../requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ../../database/database.py ../../database/database_utils.py ../finance.py ../sentiment_analysis.py daily_pipeline.py ./

CMD ["python", "daily_pipeline.py"]