FROM python:3.11-slim

WORKDIR /app

COPY collection/daily_pipeline/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY database ./database
COPY collection/collection_utils.py ./
COPY collection/finance.py ./
COPY collection/daily_pipeline/sentiment_analysis.py ./
COPY collection/daily_pipeline/daily_pipeline.py ./
COPY collection/daily_pipeline/entrypoint.sh ./

CMD ["bash", "entrypoint.sh"]