FROM python:3.11-slim

WORKDIR /app

COPY collection/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY database ./database
COPY collection/collection_utils.py ./
COPY collection/finance.py ./
COPY collection/yearly_pipeline/yearly_pipeline.py ./

CMD ["python", "yearly_pipeline.py"]